apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jackett
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/tothmarci25/home-server
    path: k8s-manifests/infrastructure/charts/jackett
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/staging/generated-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
