apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.8.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 1
          defaultDataPath: /mnt/ssd/longhorn
        defaultBackupStore:
          backupTarget: s3://home-server-velero-backups-s@auto/longhorn-backups
          backupTargetCredentialSecret: longhorn-backup-credentials
        persistence:
          defaultClassReplicaCount: 1
        ingress:
          enabled: true
          ingressClassName: nginx
          host: longhorn.home
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
