apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: cloudflared
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      serviceAccountName: cloudflared
      automountServiceAccountToken: true
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
         # - cloudflared
         # - tunnel
          - --config
          - /etc/cloudflared/config/config.yml
          - run
        command: ["cloudflared", "tunnel"]
        volumeMounts:
        - name: cloudflared-config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: vault-secrets
          mountPath: /etc/cloudflared
          readOnly: true
      volumes:
      - name: vault-secrets
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: cloudflared-vault
      - name: cloudflared-config
        configMap:
          name: cloudflared-config
