apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflared-vault
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault-system:8200"
    roleName: "cloudflared"
    objects: |
      - objectName: "credentials.json"
        secretPath: "secret/data/cloudflared/credentials"
        secretKey: "credentials.json"
