apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cloudflared-vault
  namespace: cloudflared
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    serviceAccountTokenPath: "/var/run/secrets/kubernetes.io/serviceaccount"
    roleName: "cloudflared"
    objects: |
      - objectName: "credentials.json"
        secretPath: "kv/data/cloudflared"
        secretKey: "credentials.json"
