storages:
- name: ssd
  nodeLabel: usb.ssd
  path: /mnt/ssd
  size: 40Gi
  storageClass: local-ssd

apps:
  filebrowser:
    extraVolumeMounts:
    - mountPath: /database/filebrowser.db
      name: filebrowser-config
      subPath: filebrowser.db
    - mountPath: /config/settings.json
      name: filebrowser-config
      subPath: settings.json
    - mountPath: /srv/ssd
      name: local-ssd
    extraVolumes:
    - name: filebrowser-config
      persistentVolumeClaim:
        claimName: filebrowser-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
  jackett:
    extraVolumeMounts:
    - mountPath: /config
      name: jackett-config
    extraVolumes:
    - name: jackett-config
      persistentVolumeClaim:
        claimName: jackett-config
  plex:
    extraVolumeMounts:
    - mountPath: /config
      name: plex-config
    - mountPath: /data
      name: local-ssd
      subPath: data/media
    extraVolumes:
    - name: plex-config
      persistentVolumeClaim:
        claimName: plex-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
  qbittorrent:
    extraVolumeMounts:
    - mountPath: /config
      name: qbittorrent-config
    - mountPath: /data/torrents
      name: local-ssd
      subPath: data/torrents
    extraVolumes:
    - name: qbittorrent-config
      persistentVolumeClaim:
        claimName: qbittorrent-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
  radarr:
    extraVolumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /data
      name: local-ssd
      subPath: data
    extraVolumes:
    - name: radarr-config
      persistentVolumeClaim:
        claimName: radarr-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
  sonarr:
    extraVolumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /data
      name: local-ssd
      subPath: data
    extraVolumes:
    - name: sonarr-config
      persistentVolumeClaim:
        claimName: sonarr-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc

longhornPvcs:
- name: plex-config
  size: 10Gi
- name: radarr-config
  size: 5Gi
- name: sonarr-config
  size: 5Gi
- name: jackett-config
  size: 2Gi
- name: qbittorrent-config
  size: 2Gi
- name: filebrowser-config
  size: 1Gi
