apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: media
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/tothmarci25/home-server
    targetRevision: main
    path: k8s-manifests/overlays/production/media-apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
