apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: radarr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/tothmarci25/home-server
    path: k8s-manifests/infrastructure/charts/radarr
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../values/production/generated-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
