apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alertmanager-vault
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "alertmanager"
    audience: "vault"
    objects: |
      - objectName: "bot-token"
        secretPath: "kv/data/monitoring/telegram"
        secretKey: "bot-token"
  secretObjects:
    - secretName: alertmanager-telegram
      type: Opaque
      data:
        - objectName: bot-token
          key: bot-token
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: grafana-vault
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "grafana"
    audience: "vault"
    objects: |
      - objectName: "admin-user"
        secretPath: "kv/data/monitoring/grafana"
        secretKey: "admin-user"
      - objectName: "admin-password"
        secretPath: "kv/data/monitoring/grafana"
        secretKey: "admin-password"
  secretObjects:
    - secretName: grafana-admin
      type: Opaque
      data:
        - objectName: admin-user
          key: admin-user
        - objectName: admin-password
          key: admin-password

