storages:
- name: ssd
  nodeLabel: usb.ssd
  path: /mnt/ssd
  size: 2000Gi
  storageClass: local-ssd
- name: red
  nodeLabel: usb.red
  path: /mnt/red
  size: 8000Gi
  storageClass: local-red
- name: wd
  nodeLabel: usb.wd
  path: /mnt/wd
  size: 2000Gi
  storageClass: local-wd


apps:
  filebrowser:
    extraVolumeMounts:
    - mountPath: /database/filebrowser.db
      name: filebrowser-config
      subPath: filebrowser.db
    - mountPath: /config/settings.json
      name: filebrowser-config
      subPath: settings.json
    - mountPath: /srv/ssd
      name: local-ssd
    - mountPath: /srv/wd
      name: local-wd
    - mountPath: /srv/red
      name: local-red
    extraVolumes:
    - name: filebrowser-config
      persistentVolumeClaim:
        claimName: filebrowser-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  jackett:
    extraVolumeMounts:
    - mountPath: /config
      name: jackett-config
    extraVolumes:
    - name: jackett-config
      persistentVolumeClaim:
        claimName: jackett-config
  plex:
    extraVolumeMounts:
    - mountPath: /config
      name: plex-config
    - mountPath: /data
      name: local-ssd
      subPath: data/media
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd/media
    - mountPath: /data/red
      name: local-red
      subPath: data/red/media
    extraVolumes:
    - name: plex-config
      persistentVolumeClaim:
        claimName: plex-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  qbittorrent:
    extraVolumeMounts:
    - mountPath: /config
      name: qbittorrent-config
    - mountPath: /data/torrents
      name: local-ssd
      subPath: data/torrents
    - mountPath: /data/wd/torrents
      name: local-wd
      subPath: data/wd/torrents
    - mountPath: /data/red/torrents
      name: local-red
      subPath: data/red/torrents
    extraVolumes:
    - name: qbittorrent-config
      persistentVolumeClaim:
        claimName: qbittorrent-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  radarr:
    extraVolumeMounts:
    - mountPath: /config
      name: radarr-config
    - mountPath: /data
      name: local-ssd
      subPath: data
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd
    - mountPath: /data/red
      name: local-red
      subPath: data/red
    extraVolumes:
    - name: radarr-config
      persistentVolumeClaim:
        claimName: radarr-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
  sonarr:
    extraVolumeMounts:
    - mountPath: /config
      name: sonarr-config
    - mountPath: /data
      name: local-ssd
      subPath: data
    - mountPath: /data/wd
      name: local-wd
      subPath: data/wd
    - mountPath: /data/red
      name: local-red
      subPath: data/red
    extraVolumes:
    - name: sonarr-config
      persistentVolumeClaim:
        claimName: sonarr-config
    - name: local-ssd
      persistentVolumeClaim:
        claimName: ssd-pvc
    - name: local-wd
      persistentVolumeClaim:
        claimName: wd-pvc
    - name: local-red
      persistentVolumeClaim:
        claimName: red-pvc
longhornPvcs:
- name: plex-config
  size: 20Gi
- name: radarr-config
  size: 5Gi
- name: sonarr-config
  size: 5Gi
- name: jackett-config
  size: 2Gi
- name: qbittorrent-config
  size: 2Gi
- name: filebrowser-config
  size: 1Gi
